## Basics of Python
* Various Datatypes in Python
* Variables
* Variables assignment
* Print Formatting

## Various data types in Python

### Numbers

In [1]:
1+1

2

In [2]:
2*10

20

In [3]:
10**2

100

In [4]:
10*'str'

'strstrstrstrstrstrstrstrstrstr'

In [5]:
type(1)

int

In [6]:
type('hello')

str

In [8]:
type(True)

bool

## Variable Assignment

In [9]:
a =10

In [10]:
type(a)

int

In [11]:
a =10
b =20

In [12]:
print(a*b)

200


In [14]:
first_name = 'Sandhya'
last_name= 'Gautam'

In [16]:
print('My first name is {} and last name is {}'.format(first_name,last_name))

My first name is Sandhya and last name is Gautam


In [17]:
print('My first name is {first} and last name is {last}'.format(first =first_name,last =last_name))

My first name is Sandhya and last name is Gautam


In [18]:
len ('Sandhya')

7

In [19]:
type(1.0)

float

In [20]:
type([1,2,3,34,5])

list

## Python Data Structures and Boolean
- Boolean
- Boolean and logical operators
- Lists
- Comparison and operators
- Dictionaries
- Tuples
- Sets

### Boolean Variables 
Boolean values are the two constant objects True and False.

They are used to represent the truth values.

In numeric contexts (for e.g., when used as the argument to an arithmetic operator), they behave like the integers 0 and 1, respectively.

The built-in- function bool() can be used to cast any value to a Boolean, if the value can be interpreted as a truth value they are written as False and true, respectively

In [22]:
print(True, False)

True False


In [23]:
bool()

False

In [24]:
my_str ='Sandhya Gautam'

In [25]:
my_str.isalnum() # False because my_str doesn't has alphabets and number

False

In [26]:
string ='And123'
string.isalnum()

True

In [27]:
my_str.istitle()# whatever word i have inside the variable the first letter is capital
# i.e., Sandhya

True

In [29]:
my_str.endswith('S')


False

In [30]:
my_str.startswith('S')

True

## Boolean and Logical Operators

In [31]:
True and True

True

In [32]:
True and False

False

In [33]:
True or False

True

In [34]:
True or True

True

In [35]:
True or False

True

In [36]:
str_sample='Hello World'
my_str ='Sandhya'

In [37]:
my_str.isalnum() or str_sample.isnumeric()

True

## Lists

A list is a data structure in Python that is mutable, or changeable, ordered sequence of elements. Each element or value that is inside of a list is called an item. Just as strings are defined as characters between quotes, lists are defined by having values between squared brackets [ ]

In [38]:
lst_example=[]

In [39]:
type(lst_example)

list

In [40]:
lst =list()

In [41]:
lst =['mathematics', 'Chemistry',10,20,30]

In [42]:
type(lst)

list

## Append

In [43]:
# .append is used to add elements in the list
lst.append('Sandhya')

In [44]:
lst

['mathematics', 'Chemistry', 10, 20, 30, 'Sandhya']

In [45]:
# Indexing in list
lst[2]

10

In [46]:
lst[-1]

'Sandhya'

In [47]:
lst[1:]

['Chemistry', 10, 20, 30, 'Sandhya']

In [48]:
lst[:]

['mathematics', 'Chemistry', 10, 20, 30, 'Sandhya']

In [49]:
lst.append(['John','Bala'])

In [50]:
lst

['mathematics', 'Chemistry', 10, 20, 30, 'Sandhya', ['John', 'Bala']]

## Insert

In [57]:
# insert in a specific order
lst.insert(1,'Gautam')

In [58]:
lst #Gautam is inserted in first position 

['mathematics',
 'Gautam',
 'Gautam',
 'Chemistry',
 10,
 20,
 30,
 'Sandhya',
 ['John', 'Bala'],
 'Heelo World',
 'Hello World']

In [59]:
lst.append('Hello World')

In [60]:
lst

['mathematics',
 'Gautam',
 'Gautam',
 'Chemistry',
 10,
 20,
 30,
 'Sandhya',
 ['John', 'Bala'],
 'Heelo World',
 'Hello World',
 'Hello World']

## Extend Method

In [61]:
lst.extend([6,7])

In [62]:
lst

['mathematics',
 'Gautam',
 'Gautam',
 'Chemistry',
 10,
 20,
 30,
 'Sandhya',
 ['John', 'Bala'],
 'Heelo World',
 'Hello World',
 'Hello World',
 6,
 7]

In [84]:
lst =[1,2,3,4,5,6]

In [85]:
lst.extend([8,9])

In [86]:
lst

[1, 2, 3, 4, 5, 6, 8, 9]

In [87]:
sum(lst)

38

In [88]:
lst.pop() #by default it will pop up the last element

9

In [89]:
lst

[1, 2, 3, 4, 5, 6, 8]

In [90]:
lst.pop(0)

1

In [91]:
lst

[2, 3, 4, 5, 6, 8]

In [99]:
lst =[1,2,2,2,2,4,4,4,5,5]
lst.count(2)

4

In [107]:
lst.index(4,5,7)# say the index of the number

5

In [108]:
min(lst)

1

In [109]:
max (lst)

5

In [110]:
lst*2# 2 times it will get appended not multiplied

[1, 2, 2, 2, 2, 4, 4, 4, 5, 5, 1, 2, 2, 2, 2, 4, 4, 4, 5, 5]

In [1]:
tup =(1,2,3,4,4)

In [2]:
tup[2]=0

TypeError: 'tuple' object does not support item assignment

In [3]:
lis= [1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [4]:
lis[2]='sandhya'

In [5]:
lis

[1, 2, 'sandhya', 4, 5]

- You just saw the definition of mutable and immutable.
- In tuples you cannot assign elements after you created tuples
- But in list you can assign elements whenever you want

In [8]:
tup=(1,'sandhya','kol',23,43,(1,7,9))

In [9]:
tup

(1, 'sandhya', 'kol', 23, 43, (1, 7, 9))

In [11]:
import numpy

In [13]:
lst =[1,3,3,4,45,43]
vect = numpy.array(lst)
print('vector created from list is:',vect)

vector created from list is: [ 1  3  3  4 45 43]


In [14]:
num = range(10)
num


range(0, 10)

In [15]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


## Sets
 A set is an unordered collection data type that is iterable, mutable and and has no duplicate elements. Python's set class represents the mathematical notion of a set. This is based on a data structure known as a hash table

In [18]:
## Defining an empty set
set_var =set()
print(set_var)

set()


In [20]:
print(type(set_var))

<class 'set'>


In [21]:
set_var ={1,2,3,4,3}

In [22]:
set_var# since set doesn't contain duplicate elements, so I have 3 two times
#in above set and as a output it automatically eliminated 3 

{1, 2, 3, 4}

In [23]:
set_var ={'Avengers','Ironman','Hitman'}
print(set_var)

{'Hitman', 'Avengers', 'Ironman'}


In [26]:
# Indexing
set_var[0] # doesn't support indexing


TypeError: 'set' object does not support indexing

In [24]:
set_var.add('Hulk')

In [25]:
print(set_var)

{'Hulk', 'Hitman', 'Avengers', 'Ironman'}


In [33]:
set1 ={'Avengers','Ironman','Hitman'}
set2={'Avengers','Ironman','Hitman','Hulk2'}

In [34]:
set2.intersection(set1)

{'Avengers', 'Hitman', 'Ironman'}

In [28]:
# difference
set2.difference(set1)# removes the common elements

{'Hulk2'}

In [29]:
set2 # since my difference is not updated , so i am using difference_update below

{'Avengers', 'Hitman', 'Hulk2', 'Ironman'}

In [30]:
set2.difference_update(set1)

In [31]:
set2

{'Hulk2'}

## Dictionaries
A dictionary is a collection which is unordered, changeable and indexed. In Python, dictionaries are written with curly braces and they have keys and values.

In [35]:
xx ={}
type(xx)

dict

In [36]:
dic ={1,2,3,4,5}
type(dic)

set

In [37]:
my_dict={'Car1':'Audi','Car2':'BMW','Car3':'Mercedes Benz'}

In [38]:
type(my_dict)

dict

In [39]:
for i in my_dict:# by default it will give me keys values
    print(i)

Car1
Car2
Car3


In [40]:
for i in my_dict.values():
    print(i)

Audi
BMW
Mercedes Benz


In [41]:
# we can get both keys and values at a time
for i in my_dict.items():
    print(i)

('Car1', 'Audi')
('Car2', 'BMW')
('Car3', 'Mercedes Benz')


In [42]:
# adding items in dictionaries
my_dict['car4']='audi 2.0'

In [43]:
my_dict

{'Car1': 'Audi', 'Car2': 'BMW', 'Car3': 'Mercedes Benz', 'car4': 'audi 2.0'}

In [44]:
# can replace value
my_dict['Car1'] ='Maruti'

In [45]:
my_dict

{'Car1': 'Maruti', 'Car2': 'BMW', 'Car3': 'Mercedes Benz', 'car4': 'audi 2.0'}

## Nested dictionary

In [48]:
car1_model ={'Mercedes':1960}
car2_model ={'Audi':1970}
car3_model ={'Ambasssador':1980}

car_type ={'car1':car1_model,'car2':car2_model,'car3':car3_model}

In [49]:
print(car_type)

{'car1': {'Mercedes': 1960}, 'car2': {'Audi': 1970}, 'car3': {'Ambasssador': 1980}}


In [51]:
print(car_type['car1'])

{'Mercedes': 1960}


In [52]:
print(car_type['car1']['Mercedes'])

1960


## Tuples

In [53]:
my_tuple=('Krish','Sandhya',1,2,3)

In [54]:
my_tuple[0]= 'Naik'# tuples are immutable
# you can completely change the whole list but not element

TypeError: 'tuple' object does not support item assignment

In [55]:
my_tuple.count('Krish')

1

## Numpy
Numpy library is used to create multi dimensional arrays
An array is a set osf elements with same data type.
In python list contains heterogeneous elements but array contains homogeneous elements.

In [2]:
import numpy as np

In [57]:
my_lst=[1,2,3,4,5]
arr =np.array(my_lst)# to convert into an array

In [58]:
type(arr)

numpy.ndarray

In [60]:
arr # it is 1-D array because it has only one closed bracket.

array([1, 2, 3, 4, 5])

In [61]:
arr.shape #gives you the no.of rows and columns
# by default it will give no.of elements here because of 1-D

(5,)

In [64]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [65]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [66]:
arr.shape# 15 elements

(3, 5)

### Don't see the individual closed brackets for counting the dimensions of array it's first one or two or so on and last two or so on.

In [67]:
# remember the no. of closed brackets determine the dimension of array
arr.reshape(5,3)
# remember when reshaping the array, make sure the no.of elemets are same
# in above case no.of elements is 15.
# if you try to do arr.reshape(5,4) it will give you error. 

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [68]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

### Indexing

In [69]:
## Accessing the array element
arr =np.array([1,2,3,4,5,6,7,8,9])

In [70]:
arr[3]

4

In [4]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr1 = np.array([my_lst1,my_lst2,my_lst3])

In [5]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [6]:
arr1[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [7]:
arr1[1][0:2]

array([2, 3])

In [8]:
arr1[0:2]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [9]:
arr1[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [10]:
arr1[1:3,3:7]

array([[5, 6],
       [8, 9]])

In [11]:
# or
arr1 [1:,3:]

array([[5, 6],
       [8, 9]])

In [12]:
arr1 [1:4,2:4]

array([[4, 5],
       [6, 8]])

In [13]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [14]:
arr1[1:2]

array([[2, 3, 4, 5, 6]])

In [103]:
arr1[1:2,1:4]

array([[3, 4, 5]])

In [101]:
arr1[:1]

array([[1, 2, 3, 4, 5]])

In [104]:
arr2=np.arange(0,10)

In [105]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
arr2=np.arange(0,10,step =2)

In [107]:
arr2

array([0, 2, 4, 6, 8])

In [108]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [109]:
arr =np.array([1,2,3,4,5,6,7,8,9])

In [110]:
# copy() function and broadcasting 
arr[3:]=100

In [111]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [112]:
arr1 =arr

In [113]:
arr1[3:]=500
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [114]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [115]:
# some conditions very useful in Exploratory data analysis
val =2
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [118]:
arr[arr<300]

array([1, 2, 3])

In [116]:
arr%2

array([1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int32)

In [119]:
np.ones(4)

array([1., 1., 1., 1.])

In [120]:
np.ones((2,4),dtype =float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [121]:
np.random.randn(4,4)

array([[ 2.16764818, -1.51377451, -0.36101057,  0.21717151],
       [-0.15487442, -0.64957125,  0.12724176,  0.4070465 ],
       [-0.85147985, -0.42035545,  1.76681518, -1.07898168],
       [-0.52792409, -0.6339132 ,  1.22545861,  1.21839854]])

In [122]:
np.random.rand(3,3)

array([[0.36067694, 0.51338693, 0.69915379],
       [0.18972184, 0.90713385, 0.01832512],
       [0.75991379, 0.33732706, 0.99037019]])

In [131]:
import numpy as np

In [136]:
arr = [1,2,3,4,5,6]
print(arr[0])
arr_1= np.array(arr)
type(arr_1)

1


numpy.ndarray

In [137]:
arr_1.shape

(6,)

In [151]:
arr_1 =np.array([[1,2,3,4,5,6],[2,30,40,5,6,7],[200,300,400,500,600,700]])
arr_1

array([[  1,   2,   3,   4,   5,   6],
       [  2,  30,  40,   5,   6,   7],
       [200, 300, 400, 500, 600, 700]])

In [155]:
arr_1[0:2,2]

array([ 3, 40])

In [ ]:
array= arr_1

In [124]:
arr= [[1,2,3,4],'Sandhya']

In [125]:
arr

[[1, 2, 3, 4], 'Sandhya']

In [126]:
type(arr)

list

In [129]:
arr_ = np.array([[1 , 2]])
type(arr_)

numpy.ndarray

In [15]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [17]:
arr_1=[1,2,3,4,5,6]
arr_2=[7,8,9,0,1,2]
arr_3=[70,80,90,0,10,20]
arr_4=[10,20,30,40,50,60]
arr_full = np.array([arr_1,arr_2,arr_3,arr_4])

In [18]:
arr_full

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9,  0,  1,  2],
       [70, 80, 90,  0, 10, 20],
       [10, 20, 30, 40, 50, 60]])

In [20]:
arr_full[0:2,2:4]# 0:2 is rows and 2:4 is column

array([[3, 4],
       [9, 0]])

In [21]:
arr_full[2:4,3:6]

array([[ 0, 10, 20],
       [40, 50, 60]])

In [22]:
arr_full[1,1:]

array([8, 9, 0, 1, 2])

In [24]:
arr_full[1:,4:6]

array([[ 1,  2],
       [10, 20],
       [50, 60]])

In [25]:
arr_full[2]

array([70, 80, 90,  0, 10, 20])

In [26]:
arr_full

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9,  0,  1,  2],
       [70, 80, 90,  0, 10, 20],
       [10, 20, 30, 40, 50, 60]])

In [29]:
arr_full[0:2,0:2]

array([[1, 2],
       [7, 8]])

In [38]:
a,b =2,3
print('Hi') if a<b else print('Bye')


Hi


In [39]:
a,b =2,3
if a<b:
    print('Hi')
else:
    print('Bye')

Hi


In [42]:
var = 'ASCON'
var.lower()


'ascon'

In [44]:
'ayushi'.upper()

'AYUSHI'

In [45]:
'Ayushi'.isupper()

False

In [46]:
'ayushi'.islower()

True

In [47]:
'@yu$hi'.islower()

True

In [52]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


In [57]:
for i in range(7):#
    if i ==3:
        break
    print(i)

0
1
2


In [58]:
for i in range(7):#
    if i ==3:
        continue
    print(i)

0
1
2
4
5
6


In [63]:
if 3>1:
    print('Hello')
else:
    print('Goodbye')

Hello


In [64]:
max('flying')# y comes as output because of the ASCII values.
# y has 121 as ASCII value.

'y'

In [65]:
for number in range(4):
    print('Attempt:',number)

Attempt: 0
Attempt: 1
Attempt: 2
Attempt: 3


In [68]:
for number in range(6):
    print('Attempt:',number+1)

Attempt: 1
Attempt: 2
Attempt: 3
Attempt: 4
Attempt: 5
Attempt: 6


In [69]:
for number in range(6):
    print('Attempt:',number+1,(number+1)*'.')

Attempt: 1 .
Attempt: 2 ..
Attempt: 3 ...
Attempt: 4 ....
Attempt: 5 .....
Attempt: 6 ......


In [70]:
successful = True
for number in range(3):
    print('Attempt')
    if successful:
        print('successful')

Attempt
successful
Attempt
successful
Attempt
successful


In [71]:
successful = True
for number in range(3):
    print('Attempt')
    if successful:
        print('successful')
        break

Attempt
successful


In [73]:
successful = False
for number in range(3):
    print('Attempt')
    if successful:
        print('successful')
        break
else:
    print('Attempted 3 times but failed')

Attempt
Attempt
Attempt
Attempted 3 times but failed


In [75]:
successful = True
for number in range(3):
    print('Attempt')
    if successful:
        print('successful')
        break
else:
    print('Attempted 3 times but failed')

Attempt
successful


In [81]:
xx = False
if xx:
    print('holy')
else:
    print('get lost')

get lost
