In [1]:
# numpy is numerical python packages where we can find arrays and matrix manipulations
import numpy as np


In [2]:
l =[3,4,5,6,7,'sand']

In [3]:
type(l)

list

In [5]:
type(np.array(l))

numpy.ndarray

In [8]:
np.array([[1,2,3]],ndmin=4)
# closed brackets on output determines the dimension 

array([[[[1, 2, 3]]]])

In [7]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [9]:
np.array([[1,2,3]],ndmin=10)# creating 10-D array

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [10]:
# mat is matrix which is subclass of an array
np.mat([1,2,4])

matrix([[1, 2, 4]])

In [12]:
arr = np.array([3,4,5,6,7])
arr

array([3, 4, 5, 6, 7])

In [15]:
arr[0:3:2]

array([3, 5])

In [23]:
arr_1 =np.array([[1,2],[3,4]])
arr_1

array([[1, 2],
       [3, 4]])

In [24]:
arr_1[1][1]

4

In [25]:
arr_1 =np.array([[1,2],[3,4],[4,5]])

In [26]:
arr_1

array([[1, 2],
       [3, 4],
       [4, 5]])

In [28]:
arr_1[2][1]

5

In [29]:
np.asarray([3,4,5,7])

array([3, 4, 5, 7])

In [30]:
# convert integer into float
np.asarray([3,4,5,7], dtype =np.float32)

array([3., 4., 5., 7.], dtype=float32)

In [31]:
np.asarray([3,4,5,7], dtype =np.float64)

array([3., 4., 5., 7.])

In [32]:
np.asanyarray([1,2,3,5,6])
#here list is convert into array

array([1, 2, 3, 5, 6])

In [33]:
np.asanyarray(np.mat([1,2,3,5,6]))
# since matrix is a form of array ,'asanyarray' doesnot convert into array

matrix([[1, 2, 3, 5, 6]])

In [35]:
np.fromfunction(lambda i,j:i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [36]:
np.fromfunction(lambda i,j:i+j,(3,3),dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [37]:
np.fromfunction(lambda i,j,k:i*j*k,(3,3,2),dtype=int)
# (3,3,2) means we have 3 rows of 3*2 matrix

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

## Concept of iterator and iterable

In [39]:
for i in 5:
    print(i)

TypeError: 'int' object is not iterable

In [40]:
for i in 'sudh':
    pass

In [41]:
for i in 's':
    pass

In [42]:
for i in [2,3,4,5,5]:
    pass

In [43]:
s ='sudh'
next(s)

TypeError: 'str' object is not an iterator

In [44]:
l =[1,2,3,4,5]

In [45]:
next(l)

TypeError: 'list' object is not an iterator

In [47]:
r =range(4)
r

range(0, 4)

In [48]:
next(r)

TypeError: 'range' object is not an iterator

In [49]:
s ='sudh'
i =iter(s)
next(i)

's'

In [50]:
next(i)

'u'

In [51]:
next(i)

'd'

In [52]:
next(i)

'h'

In [54]:
next(i)# since i don't have any element in 'sudh'. So gives an error

StopIteration: 

In [55]:
for i in 'sudh':
    print(i)

s
u
d
h


In [56]:
# if any object is iterable then we can convert to iterator
#'string' is an iterable object but not iterator
# but internally it becomes iterator with the help of iter function.

In [57]:
l

[1, 2, 3, 4, 5]

In [58]:
next(l)

TypeError: 'list' object is not an iterator

In [59]:
i = iter(l)
next(i)

1

In [60]:
next(i)

2

In [61]:
next(i)

3

In [62]:
np.fromiter([1,2,3,45,5],dtype=float)

array([ 1.,  2.,  3., 45.,  5.])

In [65]:
np.fromstring('234 37432757 37674',sep=' ')

array([2.3400000e+02, 3.7432757e+07, 3.7674000e+04])

In [66]:
l =[3,4,5,6,7,8,8]
arr =np.array(l)

In [67]:
arr.ndim

1

In [68]:
arr.size

7

In [69]:
arr.shape

(7,)

In [70]:
arr.dtype

dtype('int32')

In [73]:
list(range(0,8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [75]:
list(range(0,7.6))

TypeError: 'float' object cannot be interpreted as an integer

In [76]:
np.arange(0,4.6)

array([0., 1., 2., 3., 4.])

In [77]:
np.arange(0,4.6,.3)# arange works with float numbers too while range doesn't 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5])

In [78]:
np.linspace(1,5)# trying to create numbers between 1 and 5

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [79]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [80]:
np.linspace(1,5,10000)

array([1.        , 1.00040004, 1.00080008, ..., 4.99919992, 4.99959996,
       5.        ])

In [81]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [83]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [86]:
np.ones((4,5))+1

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [87]:
np.empty((3,5))

array([[0.3, 0.6, 0.9, 1.2, 1.5],
       [1.8, 2.1, 2.4, 2.7, 3. ],
       [3.3, 3.6, 3.9, 4.2, 4.5]])

In [2]:
np.eye(5)# eigen matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
np.random.rand(3,5)

array([[0.8826787 , 0.74304106, 0.41275594, 0.93656633, 0.4157777 ],
       [0.30107459, 0.69345109, 0.96403953, 0.71379235, 0.37002969],
       [0.66608129, 0.59505656, 0.57577719, 0.28055155, 0.63275962]])

In [6]:
np.random.rand(3,5,5)

array([[[0.10968388, 0.40270152, 0.29260783, 0.40536274, 0.33466474],
        [0.70106914, 0.20448415, 0.47923722, 0.71480903, 0.3026367 ],
        [0.54362046, 0.92587331, 0.48423287, 0.65921487, 0.95320625],
        [0.55830293, 0.3613353 , 0.73683173, 0.6036235 , 0.80895538],
        [0.46128448, 0.32169023, 0.42569814, 0.19395759, 0.57487075]],

       [[0.07886989, 0.99518794, 0.08055155, 0.30861486, 0.95937849],
        [0.4487389 , 0.57227931, 0.45192103, 0.36533177, 0.22932508],
        [0.93757641, 0.74127302, 0.3626676 , 0.66190581, 0.20986328],
        [0.26387653, 0.98379943, 0.73093461, 0.02210785, 0.42870679],
        [0.1137769 , 0.57668826, 0.90818342, 0.31833654, 0.37590299]],

       [[0.09214726, 0.18167835, 0.97305634, 0.65261183, 0.86524956],
        [0.40689308, 0.26541234, 0.01702888, 0.69383581, 0.65924529],
        [0.266298  , 0.91852229, 0.77090361, 0.04280966, 0.98508114],
        [0.62286849, 0.2521025 , 0.72515605, 0.75686165, 0.73319261],
        [0.03487

In [7]:
np.random.rand(1000000,5)

array([[0.24228302, 0.2115125 , 0.15348721, 0.2879497 , 0.06224776],
       [0.54071647, 0.94546544, 0.33209043, 0.10677077, 0.7285277 ],
       [0.90261117, 0.60548614, 0.24700682, 0.43830954, 0.0806052 ],
       ...,
       [0.95643393, 0.3675886 , 0.42997623, 0.40486436, 0.54088191],
       [0.70556561, 0.50977071, 0.63908743, 0.16064814, 0.8990007 ],
       [0.47085458, 0.58682407, 0.00937312, 0.44994592, 0.11616469]])

In [8]:
np.random.randn(4,5)

array([[ 0.88820485, -0.65578666,  1.65521833, -0.59146239, -1.12891151],
       [ 0.14904399, -0.7570142 ,  1.39894103, -1.51677062,  1.37157191],
       [ 0.49477261, -1.16533266,  0.50720431,  0.34066688,  1.53205738],
       [ 0.12137918, -0.47194647,  1.05663566, -0.04592014,  0.09956587]])

In [11]:
np.random.randint(3,40,size =60)

array([20, 14, 37,  6, 11, 19, 11, 35, 30, 21,  5, 17, 17, 13,  8, 26, 26,
        4, 34, 19, 11, 25,  8, 11, 20, 21, 31, 24, 30, 28, 39, 31, 34, 14,
       33, 16, 10, 30,  4, 37, 16, 21, 35, 14, 38, 35, 14, 14, 28,  9,  9,
       12,  6,  3,  3, 17,  5, 34,  3, 21])

In [13]:
arr =np.random.randint(2,7,(4,5))

In [14]:
arr.shape

(4, 5)

In [15]:
arr

array([[2, 5, 2, 4, 5],
       [3, 2, 6, 6, 3],
       [5, 4, 4, 5, 5],
       [2, 5, 4, 3, 6]])

In [16]:
arr.reshape(1,4,5)

array([[[2, 5, 2, 4, 5],
        [3, 2, 6, 6, 3],
        [5, 4, 4, 5, 5],
        [2, 5, 4, 3, 6]]])

In [17]:
arr.reshape(10,2)

array([[2, 5],
       [2, 4],
       [5, 3],
       [2, 6],
       [6, 3],
       [5, 4],
       [4, 5],
       [5, 2],
       [5, 4],
       [3, 6]])

In [18]:
arr.max()

6

In [19]:
arr.min()

2

In [20]:
arr

array([[2, 5, 2, 4, 5],
       [3, 2, 6, 6, 3],
       [5, 4, 4, 5, 5],
       [2, 5, 4, 3, 6]])

In [22]:
arr[0,1]=222

In [23]:
arr

array([[  2, 222,   2,   4,   5],
       [  3,   2,   6,   6,   3],
       [  5,   4,   4,   5,   5],
       [  2,   5,   4,   3,   6]])

In [24]:
mat1=np.random.rand(3,3)

In [25]:
mat1

array([[0.84290775, 0.20061077, 0.16328581],
       [0.55885402, 0.6303072 , 0.17464311],
       [0.352062  , 0.08864443, 0.77173772]])

In [26]:
mat2=np.random.rand(3,3)
mat2

array([[0.82251607, 0.10392193, 0.80681659],
       [0.22012354, 0.74933057, 0.07711033],
       [0.55052977, 0.56297002, 0.96200036]])

In [27]:
mat1*mat2

array([[0.69330517, 0.02084786, 0.1317417 ],
       [0.12301692, 0.47230845, 0.01346679],
       [0.19382061, 0.04990416, 0.74241196]])

In [28]:
mat1 = np.random.randint(1,4,(3,3))
mat1

array([[3, 3, 3],
       [1, 2, 2],
       [1, 2, 1]])

In [29]:
mat2 =np.random.randint(1,4,(3,3))
mat2

array([[1, 2, 2],
       [1, 1, 1],
       [1, 1, 3]])

In [30]:
mat1*mat2 #it's doing element wise multiplication not matrix multiplication 

array([[3, 6, 6],
       [1, 2, 2],
       [1, 2, 3]])

In [31]:
mat1@mat2 # for matrix multiplication we use @
# matric multiplication means rows * columns

array([[ 9, 12, 18],
       [ 5,  6, 10],
       [ 4,  5,  7]])

In [32]:
arr/0

C:\Users\visan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [33]:
arr.T

array([[  2,   3,   5,   2],
       [222,   2,   4,   5],
       [  2,   6,   4,   4],
       [  4,   6,   5,   3],
       [  5,   3,   5,   6]])

In [34]:
arr

array([[  2, 222,   2,   4,   5],
       [  3,   2,   6,   6,   3],
       [  5,   4,   4,   5,   5],
       [  2,   5,   4,   3,   6]])

In [35]:
arr**2

array([[    4, 49284,     4,    16,    25],
       [    9,     4,    36,    36,     9],
       [   25,    16,    16,    25,    25],
       [    4,    25,    16,     9,    36]], dtype=int32)

In [36]:
np.exp(arr)

array([[7.38905610e+00, 2.59044862e+96, 7.38905610e+00, 5.45981500e+01,
        1.48413159e+02],
       [2.00855369e+01, 7.38905610e+00, 4.03428793e+02, 4.03428793e+02,
        2.00855369e+01],
       [1.48413159e+02, 5.45981500e+01, 5.45981500e+01, 1.48413159e+02,
        1.48413159e+02],
       [7.38905610e+00, 1.48413159e+02, 5.45981500e+01, 2.00855369e+01,
        4.03428793e+02]])

In [37]:
np.log10(arr)

array([[0.30103   , 2.34635297, 0.30103   , 0.60205999, 0.69897   ],
       [0.47712125, 0.30103   , 0.77815125, 0.77815125, 0.47712125],
       [0.69897   , 0.60205999, 0.60205999, 0.69897   , 0.69897   ],
       [0.30103   , 0.69897   , 0.60205999, 0.47712125, 0.77815125]])

In [38]:
np.sqrt(arr)

array([[ 1.41421356, 14.89966443,  1.41421356,  2.        ,  2.23606798],
       [ 1.73205081,  1.41421356,  2.44948974,  2.44948974,  1.73205081],
       [ 2.23606798,  2.        ,  2.        ,  2.23606798,  2.23606798],
       [ 1.41421356,  2.23606798,  2.        ,  1.73205081,  2.44948974]])

In [39]:
np.pi

3.141592653589793